### ISSUE TITLE
ERROR_INSUFFICIENT_BUFFER bug

### ISSUE THREAD

**Issue by trparky** [tylerszabo/RGB-Fusion-Tool#24] opened 2018-05-15 21:20 UTC
I downloaded the source code and compiled it in Visual Studio under .NET Framework version 4.6 and I keep getting an error that includes "ERROR_INSUFFICIENT_BUFFER". I have no idea what is causing it since I compiled it with no changes to the source code.

Any ideas?

**Comment by windows2000bug** [comment] 2018-05-15 21:29
This is a known issue typically from doing to much at once. Is anything working for you? Try pulling power from PC and try again.

**Comment by tylerszabo** [comment] 2018-05-15 21:39
I should probably throw that into the README. As @windows2000bug points out the controller can get into a bad state where only completely powering down (including disconnecting from standby power - ie. throwing the switch at the power supply) can resolve.

This is a duplicate of issue #10 (which should probably be renamed to include ERROR_INSUFFICIENT_BUFFER in the title).

**Closed by tylerszabo** 2018-05-15 21:39 UTC
