### ISSUE TITLE
Error: System.Reflection.TargetInvocationException

### ISSUE THREAD

**Issue by 4n70w4** [tylerszabo/RGB-Fusion-Tool#45] opened 2019-02-21 03:31 UTC
### Steps and Commands

`.\RGBFusionTool.exe --list`
or any other arguments

### Actual behavior

Do not work

```
Error: System.Reflection.TargetInvocationException: Адресат вызова создал исключение. ---> GLedApiDotNet.Raw.GLedAPIv1_0_0Exception: dllexp_GetMaxDivision returned 0xFFFFFFFF
   в GLedApiDotNet.Raw.GLedAPIv1_0_0Wrapper.GetMaxDivision()
   в GLedApiDotNet.RGBFusionMotherboard..ctor(GLedAPIv1_0_0Wrapper wrapperAPI)
   в GLedApiDotNet.RGBFusionMotherboard..ctor()
   --- Конец трассировки внутреннего стека исключений ---
   в System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   в System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   в System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   в System.Activator.CreateInstance(Type type, Boolean nonPublic)
   в System.Activator.CreateInstance(Type type)
   в System.Lazy`1.CreateValue()
   в System.Lazy`1.LazyInitValue()
   в System.Lazy`1.get_Value()
   в RGBFusionTool.RGBFusionMain.LazyMotherboard.get_Layout()
   в RGBFusionTool.Application.Main(String[] args)
```

## Environment

- Windows Version: 10.0.17763.0
- RGB Fusion Tool Version: 0.9.3
- Motherboard: Z390 GAMING SLI-CF
- BIOS: F7b

Hashes:

D39AB2041C3A93ECB38CE446BBBC1C3DA1E3292EC25A301E4ADF3A588EE7A8F3 GLedApi.dll
7015114DAEE108681472B156C6F8EF950EDBFC9B14AE0B2126CA3E1A4CDD9BFC GLedApiDotNet.dll
702A91752CE59B11078AB8F3428ECD1F871267D8AD45E414173CCF0A69FEE9D4 layout.ini
05FC657EB5B5D563DE7807DF6EE07FC8B89DC6F6F08EB76C30E5192429FBBDCF Mono.Options.dll
F62D13CAFD785908D663E0C95FA83497FF1C20F53C7408BCDFDB0102E0721F3E RGBFusionTool.exe
64BF4B2F0C84333E239DDA24F82BF8EAD22B7DB905C50FADE262283CA96703AD ycc.dll

**Comment by tylerszabo** [comment] 2019-02-21 05:51
Unfortunately this is what happens when Gigabyte's library doesn't recognize your motherboard. Please open a ticket and ask them update the RGB Fusion SDK with their more recent motherboards; I'm hoping if enough of us do then they'll either add support or release documentation.

I'm going to close this as a duplicate of #39

**Comment by tylerszabo** [comment] 2019-02-21 05:53
Forgot to add; thanks for attempting this and reporting it. I really want to get this working for Z390s, too.

**Closed** 2019-02-21 05:52 UTC
